const RATE = 159;
const TRIP_START = "2026-10-07";

const hotels = [
  {
    city: "Tokio",
    area: "Shinjuku",
    name: "APA Hotel Shinjuku Kabukicho Tower",
    priceUsd: 92,
    desc: "Muy bien ubicado para moverte por la Yamanote. Compacto, funcional y normalmente con tarifas bajas reservando con antelación.",
    maps: "https://www.google.com/maps/search/?api=1&query=APA+Hotel+Shinjuku+Kabukicho+Tower+Tokyo+Japan",
    img: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokio",
    area: "Asakusa",
    name: "Hotel Tavinos Asakusa",
    priceUsd: 80,
    desc: "Opción económica en zona turística, bien conectada con Ginza Line y cerca de Senso-ji.",
    maps: "https://www.google.com/maps/search/?api=1&query=Hotel+Tavinos+Asakusa+Tokyo+Japan",
    img: "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Hakone",
    area: "Gora",
    name: "K's House Hakone",
    priceUsd: 78,
    desc: "Hostel económico con ambiente tranquilo y buena conexión hacia el circuito de Hakone.",
    maps: "https://www.google.com/maps/search/?api=1&query=K%27s+House+Hakone+Japan",
    img: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kioto",
    area: "Gojo",
    name: "Sotetsu Fresa Inn Kyoto-Kiyomizu Gojo",
    priceUsd: 89,
    desc: "Muy buena relación calidad-precio y base cómoda para moverte a Gion, Kiyomizu-dera y estación de Kioto.",
    maps: "https://www.google.com/maps/search/?api=1&query=Sotetsu+Fresa+Inn+Kyoto-Kiyomizu+Gojo+Japan",
    img: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kioto",
    area: "Estación",
    name: "Hotel Keihan Kyoto Ekiminami",
    priceUsd: 96,
    desc: "A pocos minutos caminando de Kyoto Station; excelente para días con Shinkansen y salidas tempranas.",
    maps: "https://www.google.com/maps/search/?api=1&query=Hotel+Keihan+Kyoto+Ekiminami+Japan",
    img: "https://images.unsplash.com/photo-1464039397811-476f652a343b?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Hiroshima",
    area: "Centro",
    name: "EN HOTEL Hiroshima",
    priceUsd: 84,
    desc: "Ubicación práctica para Peace Park y tranvía urbano. Opción sólida para una noche de paso.",
    maps: "https://www.google.com/maps/search/?api=1&query=EN+HOTEL+Hiroshima+Japan",
    img: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Nagasaki",
    area: "Estación",
    name: "Hotel Wing Port Nagasaki",
    priceUsd: 73,
    desc: "Hotel económico cerca de la estación, útil para llegar/salir rápido rumbo al aeropuerto.",
    maps: "https://www.google.com/maps/search/?api=1&query=Hotel+Wing+Port+Nagasaki+Japan",
    img: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Osaka",
    area: "Midosuji",
    name: "APA Hotel & Resort Midosuji Hommachi Eki Tower",
    priceUsd: 88,
    desc: "Precio contenido, excelente conexión por metro y acceso rápido a Namba/Umeda.",
    maps: "https://www.google.com/maps/search/?api=1&query=APA+Hotel+and+Resort+Midosuji+Hommachi+Eki+Tower+Osaka+Japan",
    img: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Osaka (USJ)",
    area: "Universal City",
    name: "La'gent Hotel Osaka Bay",
    priceUsd: 96,
    desc: "Muy buena opción cerca de USJ para mantener el presupuesto por debajo de $100.",
    maps: "https://www.google.com/maps/search/?api=1&query=La%27gent+Hotel+Osaka+Bay+Japan",
    img: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Osaka (USJ)",
    area: "Universal City",
    name: "J-Hoppers Osaka Universal",
    priceUsd: 64,
    desc: "Hostel muy económico para mantener el presupuesto bajo y dedicar más dinero a entradas/express pass de USJ.",
    maps: "https://www.google.com/maps/search/?api=1&query=J-Hoppers+Osaka+Universal+Japan",
    img: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
  },
];

const TRAVELERS = 2;
const BUDGET_REFERENCE_DAYS = 14;

const budgetItems = [
  { cat: "Vuelos Internacionales", usd: 1200, shareable: false, scalesWithDays: false },
  { cat: "Alojamiento (habitación doble)", usd: 900, shareable: true, scalesWithDays: true },
  { cat: "Transporte (JR, IC y tramos largos)", usd: 620, shareable: false, scalesWithDays: true },
  { cat: "Gastronomía & Cenas", usd: 550, shareable: false, scalesWithDays: true },
  { cat: "Actividades & Entradas (USJ + museos)", usd: 420, shareable: false, scalesWithDays: true },
  { cat: "Extras Compartidos (WiFi, taxi, lavandería)", usd: 180, shareable: true, scalesWithDays: true },
];

const cashPlan = {
  personTripRangeJpy: [100000, 140000],
  dailyCarryRangeJpy: [15000, 20000],
  emergencyJpy: 30000,
  criticalCashPoints: [
    "Templos/santuarios y entradas pequeñas en efectivo",
    "Puestos de comida, mercados y tabernas pequeñas",
    "Transporte/locales en zonas menos urbanas (Hakone, Miyajima, Nagasaki fuera de zona turística)",
    "Máquinas de tickets/taquillas y negocios sin terminal internacional",
    "Taxis y buses fuera de centros urbanos (siempre confirmar antes de subir)",
  ],
  criticalByDay: [
    "D1 Tokio: Omoide Yokocho e izakayas pequeños (frecuente solo efectivo).",
    "D4 Tokio (Tsukiji): puestos/mercados donde el efectivo sigue siendo útil.",
    "D5 Kamakura/Enoshima: puestos locales, snacks y compras pequeñas.",
    "D6 Hakone: traslados locales y paradas fuera de estación principal.",
    "D13 Hiroshima/Miyajima: ferry, snacks y tiendas en isla.",
    "D14 Nagasaki: taxis, buses o comercios sin terminal internacional.",
  ],
};

const safetyResearch = {
  updatedAt: "22 marzo 2026",
  highRiskZones: ["Kabukicho", "Roppongi", "Shibuya", "Ikebukuro"],
  commonScams: [
    "Invitaciones de 'touts' a bares/clubes con cargos inflados o de entrada no informados.",
    "Drink spiking + cobros altos en tarjeta cuando la persona pierde memoria de la noche.",
    "Clonado/uso indebido de tarjetas en locales nocturnos con terminal fuera de vista.",
    "Disputas por cuenta en bares (si no validas precios antes de entrar).",
  ],
  antiScamTips: [
    "Nunca acompañes a promotores de calle a bares o clubes, aunque prometan entrada gratis.",
    "Pide ver menú con precios y cargo de entrada antes de sentarte o pedir bebidas.",
    "No aceptes tragos de desconocidos y no dejes tu bebida sin vigilancia.",
    "Paga con tarjeta solo cuando puedas ver el terminal y revisa notificaciones del banco al instante.",
    "Si hay cobro dudoso, pide factura detallada, guarda recibos y llama al 110 para dejar constancia.",
    "Para salir de zonas de ocio tarde, usa apps oficiales de taxi o tren y evita negociar en la calle.",
  ],
  moneySafety: [
    "Japón sigue teniendo lugares 'cash only', sobre todo en zonas rurales y algunos negocios pequeños.",
    "Lleva efectivo diario suficiente para transporte local, comida rápida y pequeños gastos imprevistos.",
    "Antes de ir a zonas menos urbanas (Hakone, Miyajima, Nagasaki fuera del centro), confirma método de pago.",
    "Mantén una reserva de emergencia separada para cuando falle la tarjeta o el lector.",
  ],
  emergencyContacts: [
    { title: "Policía", value: "110", note: "Emergencia inmediata." },
    { title: "Bomberos/Ambulancia", value: "119", note: "Emergencias médicas o incendio." },
    { title: "Consulta policial", value: "#9110", note: "Línea no urgente de asesoría policial en Japón." },
  ],
  realisticPrices: [
    {
      category: "Transporte",
      item: "Willer Express Bus (Tokyo-Osaka)",
      yen: "¥4,000 - ¥8,000 (por trayecto/persona)",
      usdFromJpy: [4000, 8000],
      usdMode: "range",
      note: "Alternativa low-cost. El 'Bus Pass' se descontinúa en 2025; para 2026 se compran tickets sueltos.",
    },
    {
      category: "Transporte",
      item: "Tokyo Metro boleto sencillo",
      yen: "¥180 / ¥210 / ¥260 / ¥300 / ¥330",
      usdFromJpy: [180, 210, 260, 300, 330],
      usdMode: "range",
      note: "Tarifa según distancia en la red Tokyo Metro.",
    },
    {
      category: "Transporte",
      item: "Tokyo Subway Ticket (turista)",
      yen: "24h ¥1,000 · 48h ¥1,500 · 72h ¥2,000",
      usdFromJpy: [1000, 1500, 2000],
      usdMode: "list",
      note: "Tarifas vigentes tras revisión indicada por Tokyo Metro (14 mar 2026).",
    },
    {
      category: "Transporte",
      item: "Welcome Suica",
      yen: "Carga inicial: ¥1,000 o ¥2,000",
      usdFromJpy: [1000, 2000],
      usdMode: "or",
      note: "Sin depósito, válida 28 días, saldo restante no reembolsable.",
    },
    {
      category: "Transporte",
      item: "ICOCA para turistas (Kansai)",
      yen: "¥2,000 iniciales (incluye ¥500 depósito + ¥1,500 saldo)",
      usdFromJpy: [2000],
      usdMode: "list",
      note: "Disponible en máquinas/estaciones del área JR West.",
    },
    {
      category: "Entradas",
      item: "Kinkaku-ji (Kioto)",
      yen: "Adulto ¥500 · Primaria/secundaria ¥300",
      usdFromJpy: [500, 300],
      usdMode: "list",
      note: "Tarifa oficial del templo.",
    },
    {
      category: "Entradas",
      item: "Hiroshima Peace Memorial Museum",
      yen: "Adulto ¥200 · Secundaria superior ¥100",
      usdFromJpy: [200, 100],
      usdMode: "list",
      note: "Entrada muy accesible; menores de secundaria usualmente gratis.",
    },
    {
      category: "Entradas",
      item: "Nagasaki Atomic Bomb Museum",
      yen: "Adulto ¥200 · Primaria/secundaria ¥100",
      usdFromJpy: [200, 100],
      usdMode: "list",
      note: "Tarifa oficial reportada por turismo de Nagasaki.",
    },
    {
      category: "Parques",
      item: "Universal Studios Japan",
      yen: "Tarifa dinámica por fecha",
      usd: "Variable",
      note: "Sin precio fijo: revisar calendario oficial antes de comprar.",
    },
  ],
  extraCostAlerts: [
    {
      title: "Japan Bus Pass (Willer)",
      detail: "¡Atención! Ventas finalizan en sep 2025. Para oct 2026 NO existirá este pase.",
      impact:
        "Debes comprar billetes individuales (~¥5,000). Sigue siendo mucho más barato que el Shinkansen (¥14,500).",
    },
    {
      title: "Impuesto de alojamiento en Kioto (por persona/noche)",
      detail:
        "¥200 (<¥6,000), ¥400 (¥6,000-¥19,999), ¥1,000 (¥20,000-¥49,999), ¥4,000 (¥50,000-¥99,999), ¥10,000 (>=¥100,000).",
      impact: "No siempre aparece separado al comparar hoteles; revisa el detalle final de la reserva.",
    },
    {
      title: "KANSAI ONE PASS",
      detail: "Nueva emisión finalizada desde 30 nov 2025; en 2026 solo se vende hasta agotar stock.",
      impact: "No bases todo el plan en conseguirlo; prepara alternativa con ICOCA normal.",
    },
    {
      title: "Pagos móviles internacionales",
      detail: "Algunas apps/pagos de móvil extranjeros pueden no funcionar en Japón según el comercio/modelo.",
      impact: "Lleva siempre opción B: tarjeta física + efectivo.",
    },
  ],
  spendBenchmark: {
    title: "Gasto promedio de visitante internacional (dato oficial 2025)",
    detail: "Referencia oficial: ~¥227,000 a ¥229,000 por visitante en viaje completo.",
    note: "Tu plan de 15 días con ciudades múltiples y parque temático suele quedar por encima del promedio si incluyes vuelos internos y entradas premium.",
  },
  sources: [
    {
      label: "FCDO Japón: seguridad y fraude nocturno",
      url: "https://www.gov.uk/foreign-travel-advice/japan/safety-and-security",
    },
    {
      label: "Policía de Tokio: evitar delitos en zonas de ocio",
      url: "https://www.keishicho.metro.tokyo.lg.jp/multilingual/english/safe_society/victim_of_crime/hankagai.html",
    },
    {
      label: "JNTO: pagos cashless y límites reales",
      url: "https://www.japan.travel/en/plan/cashless-payments-in-japan/",
    },
    { label: "JR Pass oficial: precios", url: "https://japanrailpass.net/en/purchase/price/" },
    { label: "Willer Express (Japan Bus Pass)", url: "https://willerexpress.com/en/" },
    {
      label: "Tokyo Metro: tarifas regulares",
      url: "https://www.tokyometro.jp/lang_en/ticket/types/regular/index.html",
    },
    { label: "Tokyo Subway Ticket (turista)", url: "https://www.tokyometro.jp/tst/en/index.html" },
    {
      label: "Welcome Suica: compra y condiciones",
      url: "https://www.jreast.co.jp/multi/en/welcomesuica/purchase.html",
    },
    { label: "ICOCA: guía JR West", url: "https://www.westjr.co.jp/global/en/howto/icoca/" },
    { label: "KANSAI ONE PASS: aviso de ventas", url: "https://kansaionepass.com/en/about.html" },
    { label: "Kinkaku-ji: acceso y tarifas", url: "https://www.shokoku-ji.jp/en/kinkakuji/access/" },
    { label: "Hiroshima Peace Memorial Museum", url: "https://peace-tourism.com/en/spot/entry-40.html" },
    { label: "Nagasaki Atomic Bomb Museum", url: "https://en.at-nagasaki.jp/barrierfree/64034" },
    { label: "Kioto: impuesto de alojamiento", url: "https://www.city.kyoto.lg.jp/gyozai/page/0000236942.html" },
    { label: "Agencia de Turismo de Japón: gasto visitante", url: "https://www.mlit.go.jp/kankocho/news02_00071.html" },
  ],
};

const travelReadiness = {
  mustPack: [
    "Pasaporte vigente + copia digital en nube y copia física separada.",
    "Tarjeta principal + tarjeta de respaldo (idealmente de bancos distintos).",
    "Efectivo inicial en JPY para transporte/comida al llegar (mínimo primer día).",
    "eSIM/SIM activa + cargador + power bank para mapas y traducción.",
    "Seguro de viaje con cobertura médica y número de asistencia internacional.",
    "Medicinas personales con receta/certificado si aplica (Japón es estricto con fármacos).",
    "Adaptador de enchufe Tipo A y cable extra para evitar compras de urgencia.",
    "Calzado cómodo e impermeable ligero (octubre puede tener lluvia puntual).",
  ],
  watchOutGeneral: [
    "Último tren: revisarlo cada noche para no terminar pagando taxi caro.",
    "Bares/clubes: no entrar sin menú con precios y cover charge claro.",
    "Pagos: evita entregar la tarjeta fuera de tu vista.",
    "Reservas críticas (USJ, miradores, trenes populares): confirmar horario y QR con antelación.",
    "Maletas/documentos: usar taquillas oficiales y no dejar mochilas sin supervisión.",
    "Clima: tifones/lluvias pueden alterar rutas; revisar alertas el mismo día.",
  ],
  itineraryAttentionByDay: [
    "D1 Tokio (llegada 22:00): validar último tren desde Haneda y alternativa nocturna.",
    "D3 Shibuya: aglomeraciones fuertes; mochila al frente y bolsillos seguros.",
    "D4 Tokio (teamLab): alta demanda; reservar horario y llegar con margen.",
    "D6 Hakone: revisar horarios de teleférico/barco y clima antes de subir.",
    "D10 Nara: cuidado con ciervos y comida en mano (pueden empujar/morder).",
    "D12 USJ: alta demanda; entrar temprano y asegurar pases/slots en app.",
    "D13 Hiroshima-Miyajima: validar último ferry/tren de regreso para no correr.",
    "D14 Nagasaki -> Haneda: traslado crítico, confirma vuelo doméstico y terminal internacional.",
    "D15 Salida 00:05 (HND): check-in y control deben quedar listos desde la noche anterior.",
  ],
};

const itineraryData = [
  {
    day: 1,
    title: "Aterrizaje y Luces de Shinjuku",
    city: "Tokio",
    schedule: [
      {
        h: "22:00",
        t: "Llegada al Aeropuerto de Haneda (HND)",
        d: "Llegada nocturna. Pasa migración y equipaje en Terminal 3; si hay fila larga, prioriza primero salida del aeropuerto y luego compras/canje de servicios.",
        maps: "https://www.google.com/maps/place/Haneda+Airport+Terminal+3/@35.5485644,139.7845734,17z",
      },
      {
        h: "23:00",
        t: "Migración, equipaje y conectividad en Haneda",
        d: "Recoge Pocket WiFi/SIM si el mostrador sigue abierto, retira efectivo en ATM (7-Bank/Japan Post) y compra/carga una IC Card (Welcome Suica/PASMO).",
        maps: "https://www.google.com/maps/place/Haneda+Airport+Terminal+3/@35.5485644,139.7845734,17z",
      },
      {
        h: "23:45",
        t: "Traslado Haneda -> Shinjuku (Keikyu + JR / Taxi nocturno)",
        d: "Si alcanzas último tren, usa Keikyu hasta Shinagawa + JR Yamanote (45-55 min, ¥700-¥900). Si no, usa Airport Limousine Bus o taxi nocturno para llegar directo al hotel.",
        maps: "https://www.google.com/maps/place/Haneda+Airport+Terminal+3+Station/@35.5495838,139.7871645,17z",
        attention: true,
      },
      {
        h: "00:45",
        t: "Check-in tardío y cena ligera en Shinjuku",
        d: "Check-in de madrugada en Shinjuku Prince Hotel. Cena rápida en konbini 24h o ramen cercano que siga abierto para descansar y arrancar fuerte el Día 2.",
        maps: "https://www.google.com/maps/place/Ichiran+Shinjuku+Central+East+Exit/@35.6918809,139.7022205,17z",
        cash: true,
      },
    ],
  },
  {
    day: 2,
    title: "Del Tokio Edo al Tokio Otaku",
    city: "Tokio",
    schedule: [
      {
        h: "08:00",
        t: "Templo Senso-ji y Asakusa",
        d: "Toma el metro línea Marunouchi a Kanda, transbordo a línea Ginza hasta Asakusa. Cruza la enorme linterna de la Puerta Kaminarimon. Al llegar temprano evitas las hordas de turistas. Prueba el pan de melón (Melonpan) en Asakusa Kagetsudo Honten.",
        maps: "https://www.google.com/maps/place/Sens%C5%8D-ji/@35.7147651,139.7966553,17z",
      },
      {
        h: "12:00",
        t: "Kappabashi (Calle de la Cocina)",
        d: "Camina 10 min al oeste de Senso-ji. Esta calle vende todos los cuchillos, cerámicas y asombrosas réplicas de comida de plástico (sampuru) que usan los restaurantes. Compra aquí unos palillos grabados.",
        maps: "https://www.google.com/maps/place/Kappabashi+Dogu+Street/@35.7153624,139.7886475,17z",
      },
      {
        h: "14:00",
        t: "Parque Ueno y Ameyoko",
        d: "Toma el metro (línea Ginza) hasta Ueno. Da un breve paseo por el parque y adéntrate en Ameyoko, el bullicioso mercado callejero bajo las vías del tren. Ideal para comer Takoyaki o un tazón de mariscos fresco por poco dinero.",
        maps: "https://www.google.com/maps/place/Ameyoko+Shopping+District/@35.7099719,139.7745771,17z",
      },
      {
        h: "16:30",
        t: "Akihabara (Electric Town)",
        d: "Sigue caminando desde Ueno hacia el sur hasta llegar a Akihabara. Entra al edificio Radiokaikan para ver pisos enteros de figuras y cartas coleccionables. Visita Super Potato para videojuegos retro.",
        maps: "https://www.google.com/maps/place/Akihabara+Radio+Kaikan/@35.698305,139.7716943,18z",
      },
      {
        h: "20:00",
        t: "Cena: Gyukatsu Motomura",
        d: "Dirígete al Gyukatsu Motomura en Akihabara. Sirven filetes de ternera empanados por fuera y crudos por dentro; tú mismo terminas de cocinarlos en una piedra caliente en tu mesa (aprox ¥1,600).",
        maps: "https://www.google.com/maps/place/Gyukatsu+Motomura+Akihabara/@35.6987116,139.7718049,18z",
      },
    ],
  },
  {
    day: 3,
    title: "Moda, Bosques Sagrados y el Cruce",
    city: "Tokio",
    schedule: [
      {
        h: "09:00",
        t: "Santuario Meiji Jingu",
        d: "Línea Yamanote de JR hasta la estación Harajuku. Cruza el inmenso torii de madera hacia el bosque. Es un respiro de paz absoluto en medio del frenesí de Tokio.",
        maps: "https://www.google.com/maps/place/Meiji+Jingu/@35.6763976,139.6993259,17z",
      },
      {
        h: "11:00",
        t: "Takeshita Street en Harajuku",
        d: "A pasos del santuario está el epicentro de la moda Kawaii. La calle estará llenísima. Compra un crepe gigante (Marion Crepes) o visita una tienda de Purikura (fotomatones japoneses que alteran la cara).",
        maps: "https://www.google.com/maps/place/Takeshita+Street/@35.6715694,139.7030804,18z",
      },
      {
        h: "13:30",
        t: "Comida: Sushi en Omotesando",
        d: "Baja por la elegante avenida Omotesando. Come en el famoso Heiroku Sushi, una cinta transportadora clásica con excelente relación calidad-precio.",
        maps: "https://www.google.com/maps/place/Heiroku+Sushi+Omotesando/@35.6672323,139.7058567,18z",
      },
      {
        h: "15:30",
        t: "El Cruce de Shibuya y Hachiko",
        d: "Camina o toma el tren una parada a Shibuya. Sal por Hachiko Exit para ver la famosa estatua del perro. Luego cruza el paso de peatones más concurrido del mundo. Sube a Shibuya Scramble Square para verlo desde arriba.",
        maps: "https://www.google.com/maps/place/Shibuya+Crossing/@35.658514,139.70133,18z",
        attention: true,
      },
      {
        h: "17:30",
        t: "Atardecer en Shibuya Sky",
        d: "Sube al rascacielos Shibuya Sky (requiere reserva online con semanas de antelación). Las vistas al aire libre en la azotea al caer el sol son inigualables.",
        maps: "https://www.google.com/maps/place/SHIBUYA+SKY/@35.6584281,139.7021171,17z",
      },
      {
        h: "20:00",
        t: "Cena y Exploración: Center Gai",
        d: "Adéntrate en Shibuya Center-Gai para cenar. Sugerencia: Uobei Shibuya Dogenzaka, donde pides sushi por pantalla y te llega rapidísimo por un carril magnético.",
        maps: "https://www.google.com/maps/place/Uobei+Shibuya+Dogenzaka/@35.6596328,139.6974955,18z",
        attention: true,
      },
    ],
  },
  {
    day: 4,
    title: "Tokio de Contrastes: Tsukiji, Ginza y Odaiba",
    city: "Tokio (Centro y Bahía)",
    schedule: [
      {
        h: "08:00",
        t: "Desayuno en Tsukiji Outer Market",
        d: "Empieza el día en Tsukiji con sushi fresco, tamagoyaki y puestos callejeros. Es ideal llegar temprano para evitar filas y encontrar mejor variedad.",
        maps: "https://www.google.com/maps/place/Tsukiji+Outer+Market/@35.6654866,139.7706408,17z",
        cash: true,
      },
      {
        h: "10:30",
        t: "Jardines Hamarikyu",
        d: "Pasea por este jardín tradicional entre rascacielos y toma un té matcha en la casa de té dentro del parque para una pausa tranquila.",
        maps: "https://www.google.com/maps/place/Hamarikyu+Gardens/@35.6595248,139.7634015,17z",
      },
      {
        h: "13:00",
        t: "Ginza y compras urbanas",
        d: "Recorre Ginza: grandes almacenes, papelerías premium y tiendas icónicas como UNIQLO/GU. Buen punto para compras de regalos y tax-free.",
        maps: "https://www.google.com/maps/place/Ginza/@35.671702,139.764847,16z",
      },
      {
        h: "16:30",
        t: "teamLab Planets TOKYO",
        d: "Experiencia inmersiva de arte digital en Toyosu. Requiere entrada con horario; conviene reservar con antelación para asegurar franja.",
        maps: "https://www.google.com/maps/place/teamLab+Planets+TOKYO/@35.6491148,139.7897942,17z",
        attention: true,
      },
      {
        h: "19:30",
        t: "Odaiba de noche",
        d: "Cierra el día en la bahía de Tokio con vista al Rainbow Bridge y paseo por la zona costera. Ambiente ideal para fotos nocturnas.",
        maps: "https://www.google.com/maps/place/Odaiba/@35.6272017,139.7750559,15z",
      },
    ],
  },
  {
    day: 5,
    title: "Excursión Costera: Kamakura y Enoshima",
    city: "Kamakura (desde Tokio)",
    schedule: [
      {
        h: "08:00",
        t: "Tren a Kamakura",
        d: "Sal desde Shinjuku/Shibuya rumbo a Kamakura (JR + conexión local, aprox. 1h). Llegar temprano evita colas en templos.",
        maps: "https://www.google.com/maps/place/Kamakura+Station/@35.3191904,139.5501762,17z",
      },
      {
        h: "09:30",
        t: "Gran Buda de Kamakura (Kotoku-in)",
        d: "Visita el Daibutsu de bronce al aire libre, uno de los iconos históricos más famosos de Japón.",
        maps: "https://www.google.com/maps/place/Kotoku-in/@35.3167203,139.5356072,17z",
      },
      {
        h: "11:30",
        t: "Templo Hase-dera + Komachi-dori",
        d: "Sube al mirador de Hase-dera con vistas al mar y luego recorre Komachi-dori para comer/catar street food local.",
        maps: "https://www.google.com/maps/place/Hasedera+Temple/@35.3128449,139.5315182,17z",
        cash: true,
      },
      {
        h: "14:30",
        t: "Enoden hacia Enoshima",
        d: "Toma el tren local Enoden bordeando la costa hasta Enoshima. Paseo marítimo, miradores y ambiente relajado.",
        maps: "https://www.google.com/maps/place/Enoshima+Station/@35.3111475,139.4813526,17z",
      },
      {
        h: "17:30",
        t: "Regreso a Tokio",
        d: "Vuelve a Tokio al atardecer. Cena libre en Shinjuku/Shibuya y descanso para el día de traslado a Hakone.",
        maps: "https://www.google.com/maps/place/Shinjuku+Station/@35.690921,139.700257,16z",
      },
    ],
  },
  {
    day: 6,
    title: "Escapada Termal al Monte Fuji",
    city: "Hakone",
    schedule: [
      {
        h: "08:30",
        t: "Romancecar a Hakone",
        d: "En Shinjuku, toma el tren Odakyu Romancecar (reserva previa, no cubierto por JR Pass) directo a Hakone-Yumoto (85 min). Disfruta de un bento box (Ekiben) comprado en la estación.",
        maps: "https://www.google.com/maps/place/Odakyu+Sightseeing+Service+Center,+Shinjuku+West/@35.691238,139.699661,17z",
      },
      {
        h: "10:30",
        t: "Hakone Tozan Railway",
        d: "Desde Hakone-Yumoto, toma el tren de montaña haciendo zigzag entre los bosques hasta Gora. Es uno de los trenes más escénicos de Japón.",
        maps: "https://www.google.com/maps/place/Hakone-Yumoto+Station/@35.2334237,139.1037203,17z",
      },
      {
        h: "13:00",
        t: "Owakudani (Valle Hirviente)",
        d: "Toma el teleférico desde Sounzan hasta Owakudani. Huele el azufre y come el famoso Kuro-tamago (huevo negro hervido en aguas termales) que, según la leyenda, alarga la vida 7 años.",
        maps: "https://www.google.com/maps/place/Owakudani/@35.2415161,139.0195209,16z",
        cash: true,
        attention: true,
      },
      {
        h: "15:00",
        t: "Crucero en Barco Pirata",
        d: "Baja en teleférico hasta Togendai y sube al pintoresco barco pirata para cruzar el Lago Ashi. Aquí es donde tendrás las mejores vistas del Monte Fuji reflejado en el agua, si el clima acompaña.",
        maps: "https://www.google.com/maps/place/Togendai+Station/@35.238491,138.9950795,17z",
        attention: true,
      },
      {
        h: "16:30",
        t: "Check-in Ryokan Hanaori",
        d: "Camina a tu hotel (Hakone Ashinoko Hanaori). Ponte el Yukata (kimono de algodón), relájate en el Onsen exterior y prepárate para la cena tradicional japonesa incluida en tu estadía.",
        maps: "https://www.google.com/maps/place/Hakone+Ashinoko+Hanaori/@35.2384793,139.0004147,17z",
      },
    ],
  },
  {
    day: 7,
    title: "Rumbo a la Capital Imperial",
    city: "Viaje a Kioto",
    schedule: [
      {
        h: "09:00",
        t: "Desayuno Japonés y Descenso",
        d: "Tras el desayuno en el ryokan, toma el autobús rápido desde Togendai directo a la estación de Odawara (aprox. 50 min).",
        maps: "https://www.google.com/maps/place/Odawara+Station/@35.2562477,139.1550993,17z",
      },
      {
        h: "11:00",
        t: "Shinkansen (Tren Bala) a Kioto",
        d: "Usa tu JR Pass en Odawara para tomar el Shinkansen Hikari. Reserva asiento del lado derecho del tren para intentar ver el Fuji de nuevo. El trayecto a Kioto dura unas 2 horas a más de 280 km/h.",
        maps: "https://www.google.com/maps/place/Kyoto+Station/@34.985849,135.7587667,17z",
      },
      {
        h: "14:00",
        t: "Comida: Estación de Kioto",
        d: "Llegada a Kioto. Sube a la planta 10 de la estación (Kyoto Ramen Koji) donde hay réplicas de las mejores tiendas de ramen de todo el país. Elige una y recarga energías.",
        maps: "https://www.google.com/maps/place/Kyoto+Ramen+Koji/@34.9862892,135.7573674,18z",
      },
      {
        h: "16:00",
        t: "Check-in y Paseo por Gion",
        d: "Toma el metro línea Karasuma y luego Tozai hasta la zona del Cross Hotel Kyoto. Deja las maletas y camina hacia Gion, especialmente por la calle Hanami-koji, para intentar ver Geikos y Maikos al atardecer.",
        maps: "https://www.google.com/maps/place/Hanami-koji+Street/@35.0031804,135.7745771,17z",
      },
      {
        h: "19:00",
        t: "Cena a Orillas del Río Kamo",
        d: "Cena en la calle Pontocho. Si es temporada cálida, busca un restaurante con 'Kawayuka' (terrazas de madera sobre el río). Sugerencia: Chao Chao Gyoza Sanjo Kiyamachi, económico y siempre animado.",
        maps: "https://www.google.com/maps/place/Chao+Chao+Gyoza/@35.0084534,135.7709562,18z",
      },
    ],
  },
  {
    day: 8,
    title: "Las 10,000 Puertas y Templo de Agua",
    city: "Kioto (Sur y Este)",
    schedule: [
      {
        h: "07:00",
        t: "Fushimi Inari Taisha",
        d: "Toma la línea JR Nara hasta la estación Inari. Empieza a subir la montaña a las 7 AM. Solo así podrás fotografiar los icónicos pasillos de puertas Torii sin multitudes. Sube al menos hasta el mirador intermedio (cruce Yotsutsuji).",
        maps: "https://www.google.com/maps/place/Fushimi+Inari+Taisha/@34.9671402,135.7726717,17z",
      },
      {
        h: "11:30",
        t: "Templo Kiyomizu-dera",
        d: "Trasládate al distrito de Higashiyama. Sube la cuesta Matsubara-dori hasta llegar al templo del agua pura. La enorme terraza de madera construida sin un solo clavo ofrece vistas increíbles de la ciudad.",
        maps: "https://www.google.com/maps/place/Kiyomizu-dera/@34.9948561,135.7850463,17z",
      },
      {
        h: "13:30",
        t: "Paseo por Sannenzaka y Ninenzaka",
        d: "Baja desde el templo por estas calles empedradas históricas rodeadas de casas de madera. Prueba té matcha y dulces de canela (Yatsuhashi). Haz una parada en el famoso Starbucks estilo casa tradicional en Ninenzaka.",
        maps: "https://www.google.com/maps/place/Starbucks+Coffee+Kyoto+Ninenzaka+Yasaka+Chaya/@34.9996841,135.7797825,18z",
      },
      {
        h: "16:00",
        t: "Santuario Yasaka y Parque Maruyama",
        d: "Termina el recorrido a pie llegando al Santuario Yasaka. Descansa en el Parque Maruyama, famoso por su gran sauce llorón.",
        maps: "https://www.google.com/maps/place/Yasaka+Shrine/@35.0036612,135.7785534,17z",
      },
      {
        h: "19:30",
        t: "Cena: Shabu Shabu",
        d: "Para compensar el día de caminata, disfruta de una cena All-You-Can-Eat de carne Shabu Shabu o Sukiyaki en Tajimaya, en la zona de Shijo-Kawaramachi (aprox ¥3,500).",
        maps: "https://www.google.com/maps/place/Tajimaya+Shijo+Kawaramachi/@35.0036109,135.7672153,18z",
      },
    ],
  },
  {
    day: 9,
    title: "El Pabellón Dorado y Bosque de Bambú",
    city: "Kioto (Oeste y Norte)",
    schedule: [
      {
        h: "07:30",
        t: "Bosque de Bambú de Arashiyama",
        d: "Toma la línea JR Sagano desde la estación de Kioto o Nijo hasta Saga-Arashiyama. Llega antes de las 8 AM al sendero de bambú para disfrutar del crujir de los tallos en paz.",
        maps: "https://www.google.com/maps/place/Arashiyama+Bamboo+Grove/@35.0169113,135.6713186,17z",
      },
      {
        h: "10:00",
        t: "Templo Tenryu-ji",
        d: "El sendero de bambú termina justo en la entrada norte de este templo. Su jardín zen es uno de los mejores conservados de Kioto, un ejemplo perfecto de diseño paisajístico de hace siglos.",
        maps: "https://www.google.com/maps/place/Tenryu-ji/@35.015792,135.6748443,17z",
      },
      {
        h: "12:30",
        t: "Comida: Tofu Yudofu",
        d: "Arashiyama es famoso por su Tofu. Come un set tradicional en Yudofu Sagano, un restaurante con preciosos jardines, cerca del río Katsura.",
        maps: "https://www.google.com/maps/place/Yudofu+Sagano/@35.012586,135.676344,18z",
      },
      {
        h: "15:00",
        t: "Pabellón Dorado (Kinkaku-ji)",
        d: "Toma el tren Randen (o taxi para ahorrar tiempo) hacia el norte. Contempla Kinkaku-ji, un templo Zen cubierto completamente en pan de oro brillante que se refleja en el estanque Kyoko-chi. Imprescindible a la luz del atardecer.",
        maps: "https://www.google.com/maps/place/Kinkaku-ji/@35.03937,135.7292431,17z",
      },
      {
        h: "19:00",
        t: "Cena en Nishiki Market (Zona)",
        d: "Aunque el mercado Nishiki cierra a las 18:00, las calles aledañas están llenas de restaurantes. Prueba el Okonomiyaki estilo Kansai en Donguri Kyoto.",
        maps: "https://www.google.com/maps/place/Donguri+Shijo+Karasuma/@35.0030588,135.7618991,18z",
      },
    ],
  },
  {
    day: 10,
    title: "Ciervos Sagrados y Cambio de Ciudad",
    city: "Nara y Osaka",
    schedule: [
      {
        h: "09:00",
        t: "Tren a Nara",
        d: "Toma el tren Kintetsu desde Kioto (si tu hotel está en Sanjo) o JR Nara Line. Trayecto de 45 mins. En Nara puedes moverte caminando. Al llegar compra galletas (Shika Senbei) para los cientos de ciervos que pasean libres por la ciudad.",
        maps: "https://www.google.com/maps/place/Nara+Park/@34.685047,135.8430122,16z",
        attention: true,
      },
      {
        h: "11:00",
        t: "Templo Todai-ji",
        d: "Visita el edificio de madera más grande del mundo que alberga en su interior un Buda de bronce gigante (Daibutsu) de 15 metros de altura.",
        maps: "https://www.google.com/maps/place/Todai-ji/@34.6889851,135.8398157,17z",
      },
      {
        h: "13:30",
        t: "Comida y Show de Mochi",
        d: "Vuelve hacia la estación pasando por Nakatanidou. Aquí hacen el famoso 'Mochi Pounding', machacando la masa de arroz verde a una velocidad increíble. Cómprate un mochi relleno de pasta de judía roja aún caliente.",
        maps: "https://www.google.com/maps/place/Nakatanidou/@34.6819955,135.8282365,18z",
      },
      {
        h: "16:00",
        t: "Tren hacia Osaka",
        d: "Toma el tren de línea Yamatoji directo de Nara a la estación Namba en Osaka. Haz el check-in en el Swissôtel Nankai Osaka, justo sobre la estación.",
        maps: "https://www.google.com/maps/place/Namba+Station/@34.6631895,135.4996924,16z",
      },
      {
        h: "19:00",
        t: "Dotonbori: Locura Gastronómica",
        d: "A 5 min andando del hotel. Dotonbori es una explosión de carteles de neón mecánicos gigantes. Hazte la foto con el corredor de Glico. Cena Takoyaki en la calle (Kukuru o Creo-ru) y Okonomiyaki en Chibo.",
        maps: "https://www.google.com/maps/place/Dotonbori+Glico+Sign/@34.6690422,135.5013083,18z",
      },
    ],
  },
  {
    day: 11,
    title: "Castillo, Retro y Rascacielos",
    city: "Osaka",
    schedule: [
      {
        h: "09:30",
        t: "Castillo de Osaka",
        d: "Toma la línea Tanimachi de metro. Aunque el interior es un museo moderno, el exterior, con sus inmensas murallas de piedra rodeadas de fosos, es imponente y uno de los símbolos históricos de Japón.",
        maps: "https://www.google.com/maps/place/Osaka+Castle/@34.6873153,135.5262013,17z",
      },
      {
        h: "13:00",
        t: "Shinsekai: El Barrio Retro",
        d: "Viaja en metro a la zona de Ebisucho. Este barrio anclado en los años 80 está presidido por la Torre Tsutenkaku. Es el lugar de origen del Kushikatsu (brochetas empanadas y fritas).",
        maps: "https://www.google.com/maps/place/Shinsekai/@34.652514,135.5063063,17z",
      },
      {
        h: "14:00",
        t: "Comida: Daruma Kushikatsu",
        d: "Siéntate en la barra del mítico Kushikatsu Daruma. Pide un surtido de brochetas (carne, huevo de codorniz, espárragos, queso) y báñalas en la salsa negra compartida (¡recuerda, regla de oro: prohibido mojar la misma brocheta dos veces!).",
        maps: "https://www.google.com/maps/place/Kushikatsu+Daruma+Shinsekai+Sohonten/@34.6521588,135.5055034,18z",
      },
      {
        h: "17:30",
        t: "Den Den Town y Nipponbashi",
        d: "A corta distancia está la versión de Osaka de Akihabara. Menos masificada pero igual de friki. Explora tiendas de segunda mano de tecnología y cultura pop.",
        maps: "https://www.google.com/maps/place/Nipponbashi+Denden+Town/@34.6593582,135.5057771,17z",
      },
      {
        h: "20:00",
        t: "Cena en Kuromon Ichiba o Namba",
        d: "Pasea por el mercado Kuromon (algunos puestos de marisco asado abren de noche) o cena un increíble Curry japonés espeso estilo Osaka en Jiyuken Namba.",
        maps: "https://www.google.com/maps/place/Jiyuken+Namba+Honten/@34.6657805,135.5013348,18z",
      },
    ],
  },
  {
    day: 12,
    title: "Mundos de Fantasía: Universal Studios Japan",
    city: "Osaka · Universal Studios Japan",
    schedule: [
      {
        h: "07:30",
        t: "Llegada Temprana a USJ",
        d: "Toma el tren JR Loop Line y luego Sakurajima Line hasta Universal City. Es fundamental estar 1h antes de la apertura para correr y conseguir acceso a Super Nintendo World o usar tu Express Pass comprado con meses de antelación.",
        maps: "https://www.google.com/maps/place/Universal+Studios+Japan/@34.665442,135.4323382,16z",
        attention: true,
      },
      {
        h: "09:00",
        t: "Super Nintendo World",
        d: "Compra la pulsera Power-Up Band, entra por la tubería verde hacia el Castillo de Peach. Sube a la atracción interactiva de Mario Kart: Koopa's Challenge usando gafas de Realidad Aumentada.",
        maps: "https://www.google.com/maps/place/Super+Nintendo+World/@34.6650456,135.4328574,18z",
        attention: true,
      },
      {
        h: "13:00",
        t: "Comida Temática y Harry Potter",
        d: "Come en Kinopio's Cafe (dentro de Nintendo) o ve a The Wizarding World of Harry Potter. Come en Las Tres Escobas y tómate una Cerveza de Mantequilla congelada frente al castillo de Hogwarts.",
        maps: "https://www.google.com/maps/place/The+Wizarding+World+Of+Harry+Potter/@34.6659773,135.4344445,17z",
      },
      {
        h: "16:00",
        t: "Atracciones Adicionales",
        d: "Aprovecha atracciones espectaculares exclusivas de Japón como el Hollywood Dream - The Ride (montaña rusa con música) y la zona de Minion Park.",
        maps: "https://www.google.com/maps/place/Minion+Park/@34.6644026,135.430932,18z",
      },
      {
        h: "20:00",
        t: "Cena: Universal CityWalk",
        d: "Al salir del parque, el área exterior está llena de restaurantes. Cena en Hard Rock Cafe o en alguna de las franquicias de Takoyaki del complejo 'Takoyaki Park'.",
        maps: "https://www.google.com/maps/place/Universal+Citywalk+Osaka/@34.6681023,135.4379961,18z",
      },
    ],
  },
  {
    day: 13,
    title: "Hiroshima y Miyajima: Día Histórico",
    city: "Hiroshima",
    schedule: [
      {
        h: "07:45",
        t: "Shinkansen Shin-Osaka -> Hiroshima",
        d: "Sal temprano desde Shin-Osaka hacia Hiroshima (Sakura/Hikari, aprox. 1h30). Deja equipaje en hotel o en taquilla de estación.",
        maps: "https://www.google.com/maps/place/Shin-Osaka+Station/@34.733482,135.5002862,17z",
      },
      {
        h: "10:30",
        t: "Peace Memorial Park y Museo",
        d: "Recorre el Domo de la Bomba Atómica, el parque conmemorativo y el museo. Es uno de los puntos históricos más importantes de Japón.",
        maps: "https://www.google.com/maps/place/Hiroshima+Peace+Memorial+Museum/@34.3954982,132.4536205,17z",
      },
      {
        h: "13:30",
        t: "Comida: Okonomiyaki estilo Hiroshima",
        d: "Prueba la versión local en Okonomimura (capas de fideos, huevo y salsa). Es parada gastronómica clásica.",
        maps: "https://www.google.com/maps/place/Okonomimura/@34.3933228,132.4617666,18z",
        cash: true,
      },
      {
        h: "15:30",
        t: "Miyajima e Itsukushima Shrine",
        d: "Toma JR + ferry hasta la isla de Miyajima para ver el torii flotante. Es de las postales más icónicas del país.",
        maps: "https://www.google.com/maps/place/Itsukushima+Jinja/@34.2959896,132.3198451,17z",
        cash: true,
        attention: true,
      },
      {
        h: "20:30",
        t: "Noche en Hiroshima",
        d: "Regreso al centro de Hiroshima y descanso. Día intenso de historia + paisaje.",
        maps: "https://www.google.com/maps/place/Hiroshima+Station/@34.3974475,132.4754463,17z",
        attention: true,
      },
    ],
  },
  {
    day: 14,
    title: "Nagasaki + Regreso a Tokio para salida nocturna",
    city: "Nagasaki -> Tokio (Haneda)",
    schedule: [
      {
        h: "08:00",
        t: "Traslado Hiroshima -> Nagasaki",
        d: "Viaja en Shinkansen hacia Hakata y continúa en Kamome a Nagasaki (aprox. 3h30-4h total según conexión).",
        maps: "https://www.google.com/maps/place/Nagasaki+Station/@32.750285,129.8736467,17z",
        attention: true,
      },
      {
        h: "12:30",
        t: "Peace Park y Museo de la Bomba Atómica",
        d: "Visita el parque y museo para entender el contexto histórico de Nagasaki. Es un recorrido sobrio y muy significativo.",
        maps: "https://www.google.com/maps/place/Nagasaki+Atomic+Bomb+Museum/@32.7855329,129.8642806,17z",
      },
      {
        h: "15:30",
        t: "Dejima + Shinchi Chinatown",
        d: "Recorre Dejima (puerto histórico) y luego Chinatown para probar champon o sara-udon.",
        maps: "https://www.google.com/maps/place/Shinchi+Chinatown/@32.7447201,129.8761184,17z",
      },
      {
        h: "17:30",
        t: "Traslado al Aeropuerto de Nagasaki (NGS)",
        d: "Sal con margen desde el centro hacia NGS. Es el tramo clave para no comprometer la conexión internacional de madrugada en Haneda.",
        maps: "https://www.google.com/maps/place/Nagasaki+Airport/@32.9164088,129.9138641,15z",
        attention: true,
      },
      {
        h: "19:30",
        t: "Vuelo doméstico Nagasaki -> Haneda (HND)",
        d: "Elige vuelo que aterrice idealmente antes de las 21:30 para absorber retrasos y moverte con holgura dentro de Haneda.",
        maps: "https://www.google.com/maps/place/Haneda+Airport+Terminal+3/@35.5485644,139.7845734,17z",
        attention: true,
      },
      {
        h: "21:30",
        t: "Check-in internacional y control en Haneda",
        d: "Ya en HND Terminal 3, completa check-in, equipaje y seguridad para quedar listo antes del embarque de las 00:05 del 21/oct.",
        maps: "https://www.google.com/maps/place/Haneda+Airport+Terminal+3/@35.5485644,139.7845734,17z",
        attention: true,
      },
    ],
  },
  {
    day: 15,
    title: "Salida internacional",
    city: "Tokio · Haneda (HND)",
    schedule: [
      {
        h: "00:05",
        t: "Vuelo de salida (Haneda)",
        d: "Despegue internacional desde HND. Fin del itinerario.",
        maps: "https://www.google.com/maps/place/Haneda+Airport+Terminal+3/@35.5485644,139.7845734,17z",
        attention: true,
      },
    ],
  },
];
